In [3]:
dataset = [
    ["Hot Dogs", "Buns", "Ketchup"],
    ["Hot Dogs", "Buns"],
    ["Hot Dogs", "Coke", "Chips"],
    ["Chips", "Coke"],
    ["Chips", "Ketchup"],
    ["Hot Dogs", "Coke", "Chips"]
]

In [5]:
import pandas as pd
from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()
te_ary = te.fit(dataset).transform(dataset)
df = pd.DataFrame(te_ary, columns=te.columns_)
df

    Buns  Chips   Coke  Hot Dogs  Ketchup
0   True  False  False      True     True
1   True  False  False      True    False
2  False   True   True      True    False
3  False   True   True     False    False
4  False   True  False     False     True
5  False   True   True      True    False

In [7]:
from mlxtend.frequent_patterns import fpgrowth

fpgrowth(df, min_support=0.33, use_colnames=True, verbose=1)

5 itemset(s) from tree conditioned on items ()
0 itemset(s) from tree conditioned on items (Hot Dogs)
0 itemset(s) from tree conditioned on items (Ketchup)
1 itemset(s) from tree conditioned on items (Buns)
1 itemset(s) from tree conditioned on items (Chips)
3 itemset(s) from tree conditioned on items (Coke)

    support                 itemsets
0  0.666667               (Hot Dogs)
1  0.333333                (Ketchup)
2  0.333333                   (Buns)
3  0.666667                  (Chips)
4  0.500000                   (Coke)
5  0.333333         (Buns, Hot Dogs)
6  0.333333        (Hot Dogs, Chips)
7  0.500000            (Coke, Chips)
8  0.333333         (Hot Dogs, Coke)
9  0.333333  (Coke, Hot Dogs, Chips)

In [3]:
from fpgrowth_py import fpgrowth
itemSetList = [["Hot Dogs", "Buns", "Ketchup"],
    ["Hot Dogs", "Buns"],
    ["Hot Dogs", "Coke", "Chips"],
    ["Chips", "Coke"],
    ["Chips", "Ketchup"],
    ["Hot Dogs", "Coke", "Chips"]]
freqItemSet, rules = fpgrowth(itemSetList, minSupRatio=0.33, minConf=0.6)
print(freqItemSet)

for rule in rules:
    print(rule)

[{'Buns'}, {'Hot Dogs', 'Buns'}, {'Ketchup'}, {'Coke'}, {'Coke', 'Hot Dogs'}, {'Coke', 'Chips', 'Hot Dogs'}, {'Coke', 'Chips'}, {'Hot Dogs'}, {'Chips'}, {'Chips', 'Hot Dogs'}]
[{'Buns'}, {'Hot Dogs'}, 1.0]
[{'Coke'}, {'Hot Dogs'}, 0.6666666666666666]
[{'Coke'}, {'Chips', 'Hot Dogs'}, 0.6666666666666666]
[{'Coke', 'Chips'}, {'Hot Dogs'}, 0.6666666666666666]
[{'Coke', 'Hot Dogs'}, {'Chips'}, 1.0]
[{'Chips', 'Hot Dogs'}, {'Coke'}, 1.0]
[{'Coke'}, {'Chips'}, 1.0]
[{'Chips'}, {'Coke'}, 0.75]